language: node_js
node_js:
  - "8"
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
services: 
  - mongodb
  - redis-server
env: 
  - NODE_ENV=ci
  - PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
before_install:
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test